apiVersion: v1
kind: Service
metadata:
  name: {{ include "ageband.fullname" . }}-agent
  labels:
    {{- include "ageband.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: {{ .Values.agent.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ageband.name" . }}-agent
    app.kubernetes.io/instance: {{ .Release.Name }}
---
{{- if .Values.ui.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ageband.fullname" . }}-ui
  labels:
    {{- include "ageband.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: {{ .Values.ui.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "ageband.name" . }}-ui
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
